environment: DEV

log_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: default
      filename: debug.log
      encoding: utf-8
  loggers:
    " ":
      handlers:
        - console
        - file
      level: DEBUG
      propagate: false
  root:
    level: DEBUG
    handlers:
      - console
      - file

database:
  username: test_username
  password: test_password
  port: 5446
  host: localhost
  db_name: car_service_db

rabbitmq:
  username: admin
  password: admin

security:
  secret_key: 5jEbGIulaoPQRfiVO4XZLG4rkC9IdHZH3UzBREV9GqauTtsQvPta7XsfRijHaVAD4Lk1KcJgPkgbtV1w7sydtX4IkrzOgyH2sVpS
  algorithm: HS256
  token_expire: 30  # in minutes
  refresh_token_expire: 60  # in m inutes

opensearch:
  host: "localhost"
  port: 9200
  username: admin
  password: opensearch_Admin123

redis:
  host: localhost
  port: 6379
  db: 0
